name: tests-adoptions

on:
  push:
    paths: 
    - 'adoptions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd adoptions && npm install && npm run test
