name: tests-event-bus

on:
  push:
    paths:
      - 'event-bus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd event-bus && npm install && npm run test
